# Unidad III - Sistemas de Ecuaciones Lineales

In [3]:
import numpy as np

In [355]:
a = np.array([[5,2,3],[2,7,-4],[3,-4,9.]])
b = np.array([8,-2,12.])

c = np.array([[1,0,0],[1,2,0],[3,2,1.]])
d = np.array([1,5,10.])

In [323]:
def sust_atras(a,b):
    n = len(a) - 1
    x = np.zeros_like(b)
    x[n] = b[n]/a[n,n]
    for i in range(n-1,-1,-1):
        x[i] = (b[i] - (a[i,i+1:] * x[i+1:]).sum()) /a[i,i]
    return x
    
def sust_adelante(a,b):
    n = len(a)
    x = np.zeros_like(b)
    x[0] = b[0]/a[0,0]
    for i in range(1,n):
        x[i] = (b[i] - (a[i,:i]*x[:i]).sum()) / a[i,i]
    return(x)


In [399]:
def el_gauss(a,b):
    n = len(a)
    for k in range(n):
        for i in range(k+1,n):
            m = a[i,k]/a[k,k]
            a[i,k:] -= a[k,k:] * m
            b[i] -= b[k]*m
    return sust_atras(a,b)

def lu(a):
    n = len(a)
    l = np.eye(n)
    for k in range(n):
        for i in range(k+1,n):
            m = a[i,k]/a[k,k]
            l[i,k] = m
            a[i,k:] -= a[k,k:] * m
    return l,a


In [397]:
# x = el_gauss(a,b)
a = np.array([[5,2,3],[2,7,-4],[3,-4,9.]])
l,u = lu(a)
print(l)
print(u)
print(l@u)

[[ 1.          0.          0.        ]
 [ 0.4         1.          0.        ]
 [ 0.6        -0.83870968  1.        ]]
[[ 5.          2.          3.        ]
 [ 0.          6.2        -5.2       ]
 [ 0.          0.          2.83870968]]
[[ 5.  2.  3.]
 [ 2.  7. -4.]
 [ 3. -4.  9.]]


In [773]:
def lu_ppe(a):
    n = len(a)
    l = np.eye(n)
    p = np.arange(n)
    s = np.abs(a).max(axis=1)
    for k in range(n):
        pivot = np.abs(a[k:,k]/s[k:]).argmax() + k # Eleccion del elem con mayor valor abs
        # Hay cambio de elemento pivot
        if (pivot != k):
            p[k], p[pivot] = p[pivot], p[k] # Se cambia los indices del vector de permutaciones
            a[[pivot,k],:] = a[[k,pivot],:] # Se intercambian la fila k y del nuevo pivot
            l[[pivot,k],:k] = l[[k,pivot],:k] # Lo mismo en l
        
        # Eliminacion (igual que sin pivoteo)
        for i in range(k+1,n):
            m = a[i,k]/a[k,k]
            l[i,k] = m
            a[i,k:] -= a[k,k:] * m
            
    p = np.eye(n)[p] # Creo la matriz de permutacion a partir del vector p
    return p,l,a

In [775]:
a = np.array([[2,-6,-3],[-1,3,-2],[3,1,-3.]])
print(a)
p,l,u = lu_ppe(a)
print(p)
# print(l)
# print(u)
print(l@u)
acopia = np.array([[2,-6,-3],[-1,3,-2],[3,1,-3.]])
print(p.T@l@u)

print(p@acopia)

[[ 2. -6. -3.]
 [-1.  3. -2.]
 [ 3.  1. -3.]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[ 3.  1. -3.]
 [ 2. -6. -3.]
 [-1.  3. -2.]]
[[ 2. -6. -3.]
 [-1.  3. -2.]
 [ 3.  1. -3.]]
[[ 3.  1. -3.]
 [ 2. -6. -3.]
 [-1.  3. -2.]]


In [777]:
b = np.array([-1,1,0])
y = sust_adelante(l,p@b)
print(y)
x = sust_atras(u,y)
print(x)
print(acopia@x)

[ 0.  -1.   0.5]
[-0.2         0.17142857 -0.14285714]
[-1.00000000e+00  1.00000000e+00 -5.55111512e-17]


# Unidad IV - Interpolacion

# Unidad V - Integracion Numérica