# Unidad III - Sistemas de Ecuaciones Lineales

In [ ]:
import numpy as np
import scipy
import scipy.linalg

a = np.array([[1,3,2],[1,5,0],[2,4,1]])
p,l,u = scipy.linalg.lu(a)

# print(p,l,u)
print(p)
print(l)
print(u)
print(p@l@u)



[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.5        1.         0.        ]
 [0.5        0.33333333 1.        ]]
[[ 2.          4.          1.        ]
 [ 0.          3.         -0.5       ]
 [ 0.          0.          1.66666667]]
[[1. 3. 2.]
 [1. 5. 0.]
 [2. 4. 1.]]
[1 3 2]
[2 4 1]


In [ ]:
np.array([[2,-6,-3],[-1,3,-2],[3,1,-3]])

array([[ 2, -6, -3],
       [-1,  3, -2],
       [ 3,  1, -3]])

# Unidad IV - Interpolacion

# Unidad V - Integracion Numérica