# Unidad III - Sistemas de Ecuaciones Lineales

In [1]:
import numpy as np

In [3]:
a = np.array([[5,2,3],[2,7,-4],[3,-4,9.]])
b = np.array([8,-2,12.])

c = np.array([[1,0,0],[1,2,0],[3,2,1.]])
d = np.array([1,5,10.])


[[ 5.  2.  3.]
 [ 2.  7. -4.]
 [ 3. -4.  9.]]


In [323]:
def sust_atras(a,b):
    n = len(a) - 1
    x = np.zeros_like(b)
    x[n] = b[n]/a[n,n]
    for i in range(n-1,-1,-1):
        x[i] = (b[i] - (a[i,i+1:] * x[i+1:]).sum()) /a[i,i]
    return x
    
def sust_adelante(a,b):
    n = len(a)
    x = np.zeros_like(b)
    x[0] = b[0]/a[0,0]
    for i in range(1,n):
        x[i] = (b[i] - (a[i,:i]*x[:i]).sum()) / a[i,i]
    return(x)


In [399]:
def el_gauss(a,b):
    n = len(a)
    for k in range(n):
        for i in range(k+1,n):
            m = a[i,k]/a[k,k]
            a[i,k:] -= a[k,k:] * m
            b[i] -= b[k]*m
    return sust_atras(a,b)

def lu(a):
    n = len(a)
    l = np.eye(n)
    for k in range(n):
        for i in range(k+1,n):
            m = a[i,k]/a[k,k]
            l[i,k] = m
            a[i,k:] -= a[k,k:] * m
    return l,a


In [773]:
def lu_ppe(a):
    n = len(a)
    l = np.eye(n)
    p = np.arange(n)
    s = np.abs(a).max(axis=1)
    for k in range(n):
        pivot = np.abs(a[k:,k]/s[k:]).argmax() + k # Eleccion del elem con mayor valor abs
        # Hay cambio de elemento pivot
        if (pivot != k):
            p[k], p[pivot] = p[pivot], p[k] # Se cambia los indices del vector de permutaciones
            a[[pivot,k],:] = a[[k,pivot],:] # Se intercambian la fila k y del nuevo pivot
            l[[pivot,k],:k] = l[[k,pivot],:k] # Lo mismo en l
        
        # Eliminacion (igual que sin pivoteo)
        for i in range(k+1,n):
            m = a[i,k]/a[k,k]
            l[i,k] = m
            a[i,k:] -= a[k,k:] * m
            
    p = np.eye(n)[p] # Creo la matriz de permutacion a partir del vector p
    return p,l,a

In [12]:
def cholesky(a):
    n = len(a)
    l = np.zeros_like(a)
    for i in range(n):
        l[i,i] = np.sqrt(a[i,i] - (l[i, :i]**2).sum())
        for j in range(i+1,n):
            l[j,i] = (a[j,i] - (l[j, :i]*l[i, :i]).sum() ) / l[i,i]
    return l
a = np.array([[5,2,3],[2,7,-4],[3,-4,9.]])
l = cholesky(a)
print(l)
print(l@l.T)
print(a)

[[ 2.23606798  0.          0.        ]
 [ 0.89442719  2.48997992  0.        ]
 [ 1.34164079 -2.08837026  1.68484708]]
[[ 5.  2.  3.]
 [ 2.  7. -4.]
 [ 3. -4.  9.]]
[[ 5.  2.  3.]
 [ 2.  7. -4.]
 [ 3. -4.  9.]]


In [13]:
def thomas(a,b):
    n = len(a)
    x = np.zeros_like(b)
    for i in range(1,n):
        a[i,i-1] = a[i,i-1]/a[i-1,i-1] #e
        a[i,i] -= a[i,i-1]*a[i-1,i] #f
    for i in range(1,n):
        b[i] -= b[i] * a[i,i-1]
    x[-1] = b[-1]/a[i,i]
    for i in range(n-2,-1,-1):
        x[i] = (b[i] - a[i-1,i]* b[i+1])/a[i,i]

# Unidad IV - Interpolacion

# Unidad V - Integracion Numérica